#!/usr/bin/env bash
# ==============================================================
#  GLENGARRY GLEN ROSS — say(1) radio-play staging
#  Auto-generated by glengarry_parser.py
# ==============================================================
#
# Tuning (env overrides):
#   RATE=200 ./glengarry.sh            # global base rate
#   RATE_BLAKE=230 ./glengarry.sh      # per-character override
#   LINE_PAUSE=0.1 ./glengarry.sh      # gap between lines
#   PRINT_ONLY=1 ./glengarry.sh        # print script without speaking
#   ./glengarry.sh --list              # audition the cast

RATE="${RATE:-185}"
LINE_PAUSE="${LINE_PAUSE:-0.22}"
PRINT_ONLY="${PRINT_ONLY:-0}"

trap 'killall say >/dev/null 2>&1; exit 130' INT TERM

# --- VOICES ---------------------------------------------------
voice_for() {
  case "$1" in
    BLAKE)         printf '%s' "Rocko (English (US))" ;;
    LEVENE)        printf '%s' "Shelley (English (US))" ;;
    MOSS)          printf '%s' "Eddy (English (US))" ;;
    AARONOW)       printf '%s' "Fred" ;;
    WILLIAMSON)    printf '%s' "Reed (English (US))" ;;
    ROMA)          printf '%s' "Oliver (English (UK))" ;;
    LINGK)         printf '%s' "Alex" ;;
    DETECTIVE)     printf '%s' "Lee (English (US))" ;;
    MAN)           printf '%s' "Tom (English (US))" ;;
    STAGE)         printf '%s' "Whisper" ;;
    ANNOUNCER)     printf '%s' "Good News" ;;
    *)             printf '%s' "Samantha" ;;
  esac
}

# --- RATES ----------------------------------------------------
rate_for() {
  case "$1" in
    BLAKE)   printf '%s' "${RATE_BLAKE:-215}"  ;;
    LEVENE)  printf '%s' "${RATE_LEVENE:-170}" ;;
    AARONOW) printf '%s' "${RATE_AARONOW:-140}" ;;
    STAGE)   printf '%s' "${RATE_STAGE:-155}"  ;;
    *)       printf '%s' "${RATE}"             ;;
  esac
}

# --- ENGINE ---------------------------------------------------
speak() {
  local who="$1" text="$2"
  local voice rate
  voice="$(voice_for "$who")"
  rate="$(rate_for "$who")"

  printf '\n[%s / %s]\n%s\n' "$who" "$voice" "$text"

  if [ "$PRINT_ONLY" != "1" ]; then
    /usr/bin/say -v "$voice" -r "$rate" "$text"
    sleep "$LINE_PAUSE"
  fi
}

run_scene() {
  while IFS='|' read -r who text; do
    [ -z "$who" ] && continue
    case "$who" in
      '#'*)  continue ;;
      PAUSE) sleep "$text" ;;
      *)     speak "$who" "$text" ;;
    esac
  done <<'SCENE'
ANNOUNCER|Glengarry Glen Ross.

BLAKE|Lemne'      have your           attention         for   8 moment.
STAGE|ANGLE    -   BLAKE    AT THE       FRONT       OF THE       ROOM
BLAKE|‘cause you're talking about,                       what you're talking            about,        bitching about that         sale    you     shot,         some   son of a bitch don't want to buy lang..,      somebody           don't want        what you're selling,                some broad         you're trying to screw, so on, let's talk about something important. Are they       all   here?
WILLIAMSON|All but one:
BLAKE|{checks   watch} Well, I'm going anyway. Let's talk about something impertant.
STAGE|Levene gets         up,    walks     to    a    sigetable,         on which there   is   a coftee       urn.     He   starts to take              a   cup    of    coffee.
STAGE|BLAKE       (CONT'D} Put that       coffee          down.       Coffee's for closers only,                you think I'm fuckin' with you, I am not fuckin’ with you:  I'm here from downtown, I'm here from Mitch and Murray... and I'm here on a mission of mercy. (he checks notes) Your name's Levene?  You call yourself       a    salesman,          you   son       of   a bitch...
STAGE|ANGLE    -    MOSS
STAGE|Moss    gets    up,    starts       for the door, MOSS I don't have   to listen to this shit.
BLAKE|You certainly don't, pal, ‘cause the good news is:     you're fired, The bad news is you got, all of you've got just one week to regain your jobs.    “Starting with tonight. Starting with tonight's sit... Oh: have I got your attention now? Good.   ‘Cause we're having a little contest.
STAGE|He takes   some orange “lead”       5x7    index cards out of his briefcase,
BLAKE|We're going to have a little sales conference.  And the feliow with the highest sales by the thirtieth wins firet place,  First prize is a Cadillac Eldorado.  You wanna! see second prize?
STAGE|He   reaches into his     briefcase,      takes   out a     cheap packaged   set of Japanese steak knives.
BLAKE|Second prize is a set of steak knives.  Third prize is you're fired.  You get the picture, are you laughing now?  You got people coming in that door, twenty-five minutes, Mitch and Murray paid good money, get their names, to Bell them,     You can't close the leads you're given, you can't close Bhit, you are shit... hit the bricks, pal, and beat it, ‘cause you're going out.
LEVENE|The leade    are weak.
STAGE|Pause,
BLAKE|The leads are weak!          The fuckin leads are weak?        You're weak.       TI been in the business thirty years. 12
MOSS|What's your name?
BLAKE|Fuck you, that's my name.   You know why, Mister?   ‘Cause you drove a Honda to get here tonight, I drove @ sixty-thousand dollar B.M.W.       That's my name,             and your name is you're wanting,                  and you can't play          in the    man’s      game,   you can't       Cloze them,       then     go home     and tell    your wife your troubles. Because       One   Thing     Counts      In This Life!       Get Them To Sign On The Line Which Is Dotted.                  You hear me,    you faggots,..?             I   know your war stories.               I know the bullshit excuses that are your lives.                     What do you know...?  What do you know...
STAGE|He   starts   to write       on the blackboard,
STAGE|ANGLE   -   THE    BLACKBOARD
STAGE|writes huge in chalk:               "A.B.c.*
BLAKE|A.B.C, a.  Always B.     Be ©,     Closing,       Always Be Closing
STAGE|ANGLE   -   BLAKE    IN THE FRONT           OF   THE   ROOM
STAGE|BLAKE {CONT'D} Always Be       Closing. (writes) A.T.D.A. Attention,          Interest,      Decision, Action. Attention:           Do“      have your attention! Interest:  Are you interested?   I know you are, because it's fuck- or-walk:  you elose or you hit the brick: Decision:   Have you made your decision for christ? and Action? 13
STAGE|A.1.D.A.  Get out there, you got the prospects coming in.  You think they cane in to get out of the rain?  A guy don't walk on the Tot ‘est he wants to buy: They're sitting out there, waiting to give you their money... You gonna take it? Are you man enough to take it? What is it, pal? You.   Moss.
STAGE|ANGLE   - MOSS
STAGE|looking aisgruntied
MOSS|Youtre such a hero, you're 50 rich, how come you're coming down here, waste your time with such a bunch of bums?
STAGE|ANGLE - CU BLAKE
STAGE|impassive.
STAGE|ANGLE - BLAKE HOLDS Up HIS WRIST
STAGE|shoots the cuff.     Monogramned cuff, gold cufflinks, a gold Rolex watch.
BLAKE|You see this watch...?
STAGE|ANGLE ~ BLAKE TALKING TO THE MEN
BLAKE|You see this watch? This watch cost more than your car. I made Nine Hundred Seventy Thousand Dollars last year.        What did you make?... 14
STAGE|(pause) You see, Pal...?  That's who I am, and you're nothing.  Nice Guy?  I den't give a shit.  Good Father?  Fuck you. Go home to your kids.  You want to work here?     Close,     You think this is abuse...?     You think this is abuse, you cocksucker...?        You can't take this, how can you take the       abuse that you get ona sit?    You don't like it, you leave.  Jcan   go in there, toniaht, the materials you  got, make myself fifteen thousand dollars.   Can you?   Can you? Go and do likewise.   A.I.D.A.   Get mad, you sonofabitches, get mad.    You know what it takes to sell real estate?
STAGE|He reaches into the case, takes out a pair of brass balls, in a leather jockstrap contrivance.
STAGE|GLE - INSERT
STAGE|‘the brass balls CRASHING down on the table.
STAGE|ANGLE   -   BLAKE
BLAKE|it takes brass balls te sell real estate.    You go and do likewise, gents,    The money's out there,        you pick it up,       it's yours,    you don't, Y got no sympathy       for you.     You want te geo out on those Bite tonight and close, close it's yours; not, you're gonna be shining my shoes,   And you know what you'll be saying?           Bunch of losers, eitting in a bar.  Oh, Yeah.  I used to be a salesman secit's a tough racket.
STAGE|He unrolls a poster which says,           "GLENGARRY HIGHLANDS, FLORIDA."      He holds up a stack of leads.
BLAKE|These are the new leads, these are the Glengarry Leads.  They cost a fortune, and to you they're Gold. And you don't get them,  Why? Because to give them to you is just throwing them away.  They're for the closers.
STAGE|Beat. 15
BLAKE|I won't wish you good luck, because you wouldn't know what to do with it       if you got it.
STAGE|The   CAMERA FOLLOWS Blake toward the front of the room.             He stops   next to Moss.
BLAKE|And to answer your question,           pal. Why am I here?          I came here because Mitch and Murray asked me to, they asked for a favor, I said the real favor, follow my advice, and Sire your       fucken’   ass,    because a loser is'a loser,
STAGE|He walks to the front of the room.                He hands the Glengarry poster te Williamson.
STAGE|ANGLE   = THE FACES OF THE MEN
STAGE|listening to him.        A bit stunned.
STAGE|ANGLE   -   BLAKE
STAGE|goes toward the front of the office.                Williamson brings him his coat.      They confer in whispers,           as Williamson holds his coat for him and Blake puts            it on.
STAGE|ANGLE   ~ LEVENE
STAGE|Foss next to him.
MOSS|buncha nonsense,     treat people like that...      the fuck is he gonna get off, mickeymouse "sales promotion...”
STAGE|Aaronow walks past the desk of the other two.
AARONOW|They don't mean it,        I'm svre he didn't mean it about trimming down the    sales   force.
STAGE|MOSS: .-+-and where the hell is Roma? Where is Mister Ricky Roma,           all the while, we've got to sit here, eat this nonsense... 16
STAGE|Levene gets up from his chair.              CAMERA FOLLOWS him back to another desk.     He sits,   dials the phone.
LEVENE|Helle.    This is Mr. Levene.             How 4s she doing?         Ie she awake?       The Bector came by? What did he say? Uh buh,  Uh huh, well, I cantt come in tonight.          I know she is r know she is, I... I got te go out.  You tell her... when she wakes up,      tell her I got to go out.
STAGE|We HEAR Williamson's voice.
WILLIAMSON|Gentieme n...?
LEVENE|you tell her I'11 call her from the    road.
STAGE|He hanga up.      Looks toward Williamson.
STAGE|ANGLE   - THE SALESNEN
STAGE|Williamson in the foreground, his back to the CAMERA. Williamson tekes the Glengarry poster from Blake, tacks it up on the wall. It reads, "GLENGARRY HIGHLANDS, FLORIDA," and features beautiful people having a good time. Williamson takes down the poster, xolls another, amaller poster, which reads "SALES INCENTIVE PROMOTION" and has a picture of a Cadillac, and the steak knives, and a calendar. Williamson starts filling in the numbers on the calendar. WILLIAMSON        (0.5.) You heard the man...
STAGE|MOSS     (0.5.} And what is this in aid of...?
STAGE|WILLIAMSON        (0.5.} s..a8 of tonight...
MOSS|...and what is this, excuse me...7
WILLIAMSON|what it's in aid of is that Hitch    and Murray... 5a
STAGE|ANGLE   - WILLIAMSON AND MOSS
MOSS|Fuck Mitch and Murray.        I'm doing ny job, I got to put up with this childishness...
WILLIAMSON|I didn't make the rules, I'm paid to run the office.  You don't like the rules,    Dave,    there's the door.
STAGE|Williamson starts walking through the office, distributing the lead cards.        CAMERA FOLLOWS.
WILLIAMSON|two lead cards for tonight,        two lead   cards tomorrow...
STAGE|Williamson hands a       card to Levene.
STAGE|ANGLE   -   INSERT
STAGE|fhe card in Levene's hand, worn, annetated, old.         The name is "BRUCE AND HARRIET HYBORG."
WILLIAMSON|As you heard.   End ef the month: top salesman  gets the Eldoradc, next man down the list...
STAGE|ANGLE - LEVENE AND WILLIAMSON
LEVENE|What about the good leads...
WILLIAMSON|The    leads I've given you...
LEVENE|These leads are shit,  They're old, I've seen this name at least...
WILLIAMSON|The leads are assigned randomly and you'll take what you've got. Now...
STAGE|‘LEVENE What about the new leads?
WILLIAMSON|18
LEVENE|viethe      new leads,    the   Glengarry Leads... we've got the ad in the paper, Mitch and Murray, spending money for some new leads.                 What about the Glengarry Leads?
WILLIAMSON|I've got them,          I'm gonna hold on to them,      and they'll be assigned to closers.
LEVENE|Assigned to who?
WILLIAMSON|To...      based on the sales volume, first to Roma...
MOSS|Where is Roma,         why   isn't he..
WILLIAMSON|Mr. Roma has his         leads...
MOSS|The     Glengarry Leads...          the   good leads...
WILLIAMSON|»».that's      correct.      The    good leads,     and you've got your leads, and,      as the hour is waning,           I suggest you,      those of you who are interested in & continuing job with thie organization, get to work,  ‘Thank you for your tention.
STAGE|Williamson retreats back into hie private office.  Moss starts putting on bis coat, picks up hie lead cards.
STAGE|Moss Look at this      garbage ,worked-over ++ bullshit,      bu s'posed to close tl (of lead card) Lookit this, I've had this guy before, I've been to his house twice,
AARONOW|I,   T,    I can't close this stuff... as
STAGE|(to Levene) Shelly, T mean, how am I supposed to... they're going to bounce me out of a Job...
STAGE|Raronow sighs, sits at a desk next to Levene,               picks up   a telephone, consults the card, dials.
STAGE|ANGLE    -   LEVENE
STAGE|sitting,      beaten,   at his desk,       the two lead cards in front of him on his      desk.   Also     on his    desk,   a picture of a young wonan in a frame, a little loving cup with a plaque which reads "WORLD'S GREATEST SALESMAN."   Levene sits back in his chair, lights a cigar.   In the b.g. we HEAR Aaronow, on the phone.
AARONOW|Hello, Mr. Palermo?  I'm sorry... Mr. Speece, is this Mr. Robert Sp... This is George Anronow, I'm with Rio, I spoke with your wife earlier?   I am the Vice President of Rio Rancho roperties, in Furman, Arizo... yes. I'm calling from the airport, I'm between planes, and, consulting my map, I see that you and your wife live near the airport.  I have some... rather unusual, rather good information on the property,   and    I'd...
STAGE|He continues. As Levene sighs, he picks up the lead card, “Bruce and Harriet Nyborg," begins to dial.
STAGE|ANGLE    -   INSERT
STAGE|The card.  The number, annotations "showed some                interest in retirement property."
STAGE|ANGLE    - TIGET,     LEVENE ON THE PHONE
STAGE|Aaronow’s conversation sontinues              in the b.g. 20
LEVENE|Hello,        Hello.  This       is    Sheldon Tevene.        Listen closely,          please,         I only    have     a moment.       I    can    only speak to Mrs,         Nyborg.         This    is Mrs. Nyborg?  Listen closely, please.  I'm calling from Consolidated Properties of Arizona, and our computer picked your name        at random from the thousands        who write       in   for information on         our properties. Under the        Federal   Law your          prize, as    you    know,   must be     awarded         to you whether or not you engage                      in our    Land    Investment Plan,            the    only stipulation ie that both you and your husband must sign at the same time, for the receipt of your prize.   I'm going to be, I'l] be in the Chicago area tonight and tomorrow... which time would be more convenient for me to speak with both you and your husband...?
STAGE|Aaronow in the    foreground,       Levene       in the background.
AARONOW|{on the phone) Well, what time would be more con... well, no, I only have the two... but, but, yes, but x uns.           @ you're not interested in               we're not,          what we're talking about is          investment,            in... no,    no,    if you would
STAGE|Pause.
STAGE|He hangs up the telephone.           Sighs.        Slowly gets up.    CAMERA FOLLOWS him up through the          office,       past the door to Williamson's office,       through which we eee Williamson ruling heavy lines on a board,  Aaronow walks to the front of the pffice, looks out at the street,  Next to him, Moss is finishing svaddling himself in his storm wear.
MOSS|Buncha fuckin'         nonsense,        mmm?
AARONOW|I ecan't close         tem...
STAGE|Moss Nobody can close          ‘em. 21
AARONOW|syethey're old...
STAGE|Koss They're ancient,               buncha nonsense, yet some      jerk to come in here...
AARONOW|Sometimes,             just think,         you know,           I wonder what             I'm doing          in this business...
MOSS|Send    a   guy        out there,          no   support, no   confidence.
AARONOW|..eand then,            I   say       "Nobody can close       'em," then             I   look at Roma...
MOSS|Roma,       fuck Roma,             had a    freak,         a couple,       little run of luck... these       leads       are garbage.
AARONOW|+,ethen      I       say,   then J        say,      why give him          the good leads,               he doesn't peed them
STAGE|Noss Are you going out?
AARONOW|Ican't,           I    have to go          out,      I   can't make a Bit...
MOSS|You tried...?
AARONOW|Something, there's something wrong with me, I tried both of the cards, I can't... what it ie, I can't push through...
MOSS|Get your         coat       on,       you'll   come out with me...
STAGE|Moss   throws Aaronow Aaronow's coat.
AARONOW|Something            in me... MOSS forget it...
AARONOW|I try and try,         but I     can't,   T can't    seem     to...
STAGE|voss I said foryet         it...    come on...
AARONOW|weeT    can't close      ‘em...
STAGE|Moss and Aaronow start out the front door.  In the background, we SEE Levene still on the phone.
LEVENE|Well,    then,     Mrs...     Mrs,   Nybera, U'41,    I'il call back in...            yes. Thank you.
STAGE|Levene picks up another card, dials the phone.  CAMERA PULLS BACK (outside) keeping Moss and Aaronow in the foreground.
LEVENE|{into phone) Hello,  Mrs...?
STAGE|The door swings closed.

PAUSE|1.0
ANNOUNCER|End of scene.
SCENE
}

# --- AUDITION MODE -------------------------------------------
if [[ "$1" == "--list" ]]; then
  /usr/bin/say -v "Rocko (English (US))" "BLAKE. The closer from downtown. Brings what he is."
  sleep 0.5
  /usr/bin/say -v "Shelley (English (US))" "LEVENE. Shelley the Machine Levene. Worn down."
  sleep 0.5
  /usr/bin/say -v "Eddy (English (US))" "MOSS. Dave Moss. Gravel and grievance."
  sleep 0.5
  /usr/bin/say -v "Fred" "AARONOW. George Aaronow. Already defeated."
  sleep 0.5
  /usr/bin/say -v "Reed (English (US))" "WILLIAMSON. John Williamson. Smug kid with the leads."
  sleep 0.5
  /usr/bin/say -v "Oliver (English (UK))" "ROMA. Richard Roma. Top closer. Works the long con."
  sleep 0.5
  /usr/bin/say -v "Alex" "LINGK. James Lingk. Roma's mark. Already regretting it."
  sleep 0.5
  /usr/bin/say -v "Lee (English (US))" "DETECTIVE. The detective. Flat affect, taking names."
  sleep 0.5
  /usr/bin/say -v "Tom (English (US))" "MAN. Unspecified man. Background noise."
  sleep 0.5
  /usr/bin/say -v "Whisper" "STAGE. Stage directions. Atmospheric."
  sleep 0.5
  /usr/bin/say -v "Good News" "ANNOUNCER. Announcer. Sets the scene."
  sleep 0.5
  exit 0
fi

run_scene
